output-format: grouped

strictness: high
autodetect: true
member-warnings: false

ignore-paths:
  - docs
  - build
  - tests
  - build.py

pylint:
  options:
    max-parents: 10
    disable:
      - invalid-name
      - no-self-use
      - too-many-ancestors
